---
# tasks file for cassandra
- name: Add Cassandra repo key
  apt_key:
    url: https://downloads.apache.org/cassandra/KEYS
    state: present
#    id: A278B781FE4B2BDA
#    keyserver: keyserver.ubuntu.com


- name: add repo
  apt_repository:
    repo: "{{ cassandra_repo }}"
    filename: cassandra
    state: present

- name: install cassandra
  apt:
    name: cassandra
    state: latest
    update_cache: yes
    # do not start at the end of install
    policy_rc_d: 101

- name: copy config
  template:
    src: cassandra.yaml.j2
    dest: /etc/cassandra/cassandra.yaml
    mode: '0644'
    owner: root
    group: root
  notify:
    - cassandra restart

- name: enable service
  service:
    name: cassandra
    enabled: true
    state: started